xray_tracing_enabled: true
override_throttling_config:
  queue_config:
    batch_window: 60
    batch_size: 500
    max_concurrency: 2
  lambda_rate_limit_config:
    calls_limit: 1000
    period_sec: 60
override_subgrp_config:
  queue_config:
    batch_window: 10
    batch_size: 500
    max_concurrency: 2
