Resources:
  LoadControlCancelRequestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: LoadControlCancelRequestPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: "SupportPublish"
                Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  - ${self:custom.SUPPORT_SNS_ARN}
              - Sid: "OverrideSMAccess"
                Effect: Allow
                Action:
                  - states:StopExecution
                Resource: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:execution:msi-${self:provider.stage}-dlc-override-processors-sm:*
              - Sid: "RequestTrackerDDBWriteAccess"
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: ${self:custom.REQUEST_TRACKER_TABLE_ARN}
              - Sid: "PnetSessionDDBAccess"
                Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource: ${self:custom.PNET_SESSION_TABLE_ARN}
              - Sid: "DDBReadOnlyAccess"
                Effect: Allow
                Action:
                  - dynamodb:Query
                Resource:
                  - !Sub '${self:custom.SUBSCRIPTION_TABLE_ARN}/index/subId-index'
                  - !Sub '${self:custom.REQUEST_TRACKER_TABLE_ARN}/index/GSI3'
              - Sid: "PnetSecretAccess"
                Effect: Allow
                Action:
                  - secretsmanager:GetResourcePolicy
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecretVersionIds
                Resource:
                  - ${self:custom.PNET_SECRET_ARN_PATTERN}
              - Sid: "CancelOverrideSMAccess"
                Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref DLCCancelOverrideStateMachine
              - Sid: "SubscriptionKdsWriteOnly"
                Effect: Allow
                Action:
                  - kinesis:PutRecord
                Resource: ${self:custom.KINESIS_DATA_STREAM_ARN}
